# Fork itself is paid software: please buy a license first (https://git-fork.com/buy).
# The second link supports this unofficial wrapper.
custom: ["https://git-fork.com/buy", "https://www.buymeacoffee.com/ventura8"]
