# bash completion for fork-linux and fork -*- shell-script -*-
# Generated by scripts/gen-data.py from the fork-linux argparse parser; do not edit.

_fork_linux_words() {
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -W "$1" -- "$cur")
}

_fork_linux_files() {
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -f -- "$cur")
}

_fork_linux_dirs() {
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -d -- "$cur")
}

# _fork_linux_node KEY: the options, value options, subcommands and positionals of a command.
_fork_linux_node() {
	case "$1" in
		"")
			_fl_opts='-h --help -V --version --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='setup run open update snapshot rollback settings desktop ssh git-bridge repo logs doctor uninstall status version about credits config'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"setup")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --fork-version --latest --allow-untested --wine --dotnet --accept-fork-eula --only --from-step --force --reset --no-launch --list-steps'
			_fl_vopts='--prefix --fork-version --wine --dotnet --only --from-step'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"run")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --debug --wine-debug --x11 --wayland --no-setup --no-hooks --from-file-manager'
			_fl_vopts='--prefix --wine-debug'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"open")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --debug --wine-debug --x11 --wayland --no-setup --no-hooks --from-file-manager'
			_fl_vopts='--prefix --wine-debug'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"update")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --check --fork --wine --fork-version --latest --allow-untested'
			_fl_vopts='--prefix --fork-version'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"snapshot")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='create list delete prune'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"snapshot create")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --reason'
			_fl_vopts='--prefix --reason'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"snapshot list")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"snapshot delete")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"snapshot prune")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"rollback")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --to-version --with-settings --no-pin'
			_fl_vopts='--prefix --to-version'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"settings")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='show get set unset apply-defaults backup restore path'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"settings show")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"settings get")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"settings set")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --string'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"settings unset")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"settings apply-defaults")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"settings backup")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"settings restore")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"settings path")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"desktop")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='install remove status'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"desktop install")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --file-managers --no-menu --no-icons --cli-alias'
			_fl_vopts='--prefix --file-managers'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"desktop remove")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"desktop status")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"ssh")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='sync status'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"ssh sync")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --dry-run --mode --no-config'
			_fl_vopts='--prefix --mode'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"ssh status")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"git-bridge")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='status enable disable record'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"git-bridge status")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"git-bridge enable")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --build'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"git-bridge disable")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"git-bridge record")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words='on off'
			;;
		"repo")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='check fix undo'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"repo check")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"repo fix")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --yes --no-filemode --no-symlinks'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"repo undo")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"logs")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --wine --fork --velopack --setup --all --follow -f --path --bundle'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"doctor")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --fix --deep --network --check'
			_fl_vopts='--prefix --check'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"uninstall")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root --purge --keep-downloads --yes'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"status")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"version")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"about")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"credits")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"config")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs='get set unset list path edit'
			_fl_pos=0
			_fl_pos_words=''
			;;
		"config get")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"config set")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"config unset")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
		"config list")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"config path")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		"config edit")
			_fl_opts='-h --help --json --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
			_fl_vopts='--prefix'
			_fl_subs=''
			_fl_pos=0
			_fl_pos_words=''
			;;
		*)
			_fl_opts=''
			_fl_vopts=''
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
	esac
}

# _fork_linux_value KEY OPTION: complete the value of OPTION.
_fork_linux_value() {
	case "$1|$2" in
		"|--prefix")
			_fork_linux_dirs
			;;
		"setup|--prefix")
			_fork_linux_dirs
			;;
		"setup|--fork-version")
			;;
		"setup|--wine")
			_fork_linux_words 'managed system flatpak'
			_fork_linux_files
			;;
		"setup|--dotnet")
			_fork_linux_words 'auto dotnet48 dotnet472'
			;;
		"setup|--only")
			;;
		"setup|--from-step")
			;;
		"run|--prefix")
			_fork_linux_dirs
			;;
		"run|--wine-debug")
			;;
		"open|--prefix")
			_fork_linux_dirs
			;;
		"open|--wine-debug")
			;;
		"update|--prefix")
			_fork_linux_dirs
			;;
		"update|--fork-version")
			;;
		"snapshot|--prefix")
			_fork_linux_dirs
			;;
		"snapshot create|--prefix")
			_fork_linux_dirs
			;;
		"snapshot create|--reason")
			;;
		"snapshot list|--prefix")
			_fork_linux_dirs
			;;
		"snapshot delete|--prefix")
			_fork_linux_dirs
			;;
		"snapshot prune|--prefix")
			_fork_linux_dirs
			;;
		"rollback|--prefix")
			_fork_linux_dirs
			;;
		"rollback|--to-version")
			;;
		"settings|--prefix")
			_fork_linux_dirs
			;;
		"settings show|--prefix")
			_fork_linux_dirs
			;;
		"settings get|--prefix")
			_fork_linux_dirs
			;;
		"settings set|--prefix")
			_fork_linux_dirs
			;;
		"settings unset|--prefix")
			_fork_linux_dirs
			;;
		"settings apply-defaults|--prefix")
			_fork_linux_dirs
			;;
		"settings backup|--prefix")
			_fork_linux_dirs
			;;
		"settings restore|--prefix")
			_fork_linux_dirs
			;;
		"settings path|--prefix")
			_fork_linux_dirs
			;;
		"desktop|--prefix")
			_fork_linux_dirs
			;;
		"desktop install|--prefix")
			_fork_linux_dirs
			;;
		"desktop install|--file-managers")
			;;
		"desktop remove|--prefix")
			_fork_linux_dirs
			;;
		"desktop status|--prefix")
			_fork_linux_dirs
			;;
		"ssh|--prefix")
			_fork_linux_dirs
			;;
		"ssh sync|--prefix")
			_fork_linux_dirs
			;;
		"ssh sync|--mode")
			_fork_linux_words 'link copy'
			;;
		"ssh status|--prefix")
			_fork_linux_dirs
			;;
		"git-bridge|--prefix")
			_fork_linux_dirs
			;;
		"git-bridge status|--prefix")
			_fork_linux_dirs
			;;
		"git-bridge enable|--prefix")
			_fork_linux_dirs
			;;
		"git-bridge disable|--prefix")
			_fork_linux_dirs
			;;
		"git-bridge record|--prefix")
			_fork_linux_dirs
			;;
		"repo|--prefix")
			_fork_linux_dirs
			;;
		"repo check|--prefix")
			_fork_linux_dirs
			;;
		"repo fix|--prefix")
			_fork_linux_dirs
			;;
		"repo undo|--prefix")
			_fork_linux_dirs
			;;
		"logs|--prefix")
			_fork_linux_dirs
			;;
		"doctor|--prefix")
			_fork_linux_dirs
			;;
		"doctor|--check")
			;;
		"uninstall|--prefix")
			_fork_linux_dirs
			;;
		"status|--prefix")
			_fork_linux_dirs
			;;
		"version|--prefix")
			_fork_linux_dirs
			;;
		"about|--prefix")
			_fork_linux_dirs
			;;
		"credits|--prefix")
			_fork_linux_dirs
			;;
		"config|--prefix")
			_fork_linux_dirs
			;;
		"config get|--prefix")
			_fork_linux_dirs
			;;
		"config set|--prefix")
			_fork_linux_dirs
			;;
		"config unset|--prefix")
			_fork_linux_dirs
			;;
		"config list|--prefix")
			_fork_linux_dirs
			;;
		"config path|--prefix")
			_fork_linux_dirs
			;;
		"config edit|--prefix")
			_fork_linux_dirs
			;;
		*)
			_fork_linux_files
			;;
	esac
}

_fork_linux_takes_value() {
	local option
	for option in $_fl_vopts; do
		[[ "$option" == "$1" ]] && return 0
	done
	return 1
}

_fork_linux() {
	local cur prev key="" word i skip=0 _fl_opts _fl_vopts _fl_subs _fl_pos _fl_pos_words
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev=""
	if ((COMP_CWORD > 0)); then
		prev="${COMP_WORDS[COMP_CWORD - 1]}"
	fi
	_fork_linux_node ""
	for ((i = 1; i < COMP_CWORD; i++)); do
		word="${COMP_WORDS[i]}"
		if ((skip)); then
			skip=0
			continue
		fi
		case "$word" in
			--)
				_fork_linux_files
				return 0
				;;
			-*)
				if [[ "$word" != *=* ]] && _fork_linux_takes_value "$word"; then
					skip=1
				fi
				continue
				;;
		esac
		if [[ -n "$_fl_subs" ]]; then
			key="${key:+$key }$word"
			_fork_linux_node "$key"
		fi
	done
	if ((skip)); then
		_fork_linux_value "$key" "$prev"
		return 0
	fi
	if [[ "$cur" == -* ]]; then
		_fork_linux_words "$_fl_opts"
	elif [[ -n "$_fl_subs" ]]; then
		_fork_linux_words "$_fl_subs"
	elif [[ -n "$_fl_pos_words" ]]; then
		_fork_linux_words "$_fl_pos_words"
	elif ((_fl_pos)); then
		_fork_linux_files
	fi
	return 0
}

_fork_linux_fork() {
	local cur prev
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev=""
	if ((COMP_CWORD > 0)); then
		prev="${COMP_WORDS[COMP_CWORD - 1]}"
	fi
	if [[ "$prev" == "--prefix" ]]; then
		_fork_linux_dirs
	elif [[ "$cur" == -* ]]; then
		_fork_linux_words '-h --help -V --version --prefix --gui --no-gui --offline -v --verbose -q --quiet --allow-root'
	else
		if ((COMP_CWORD == 1)); then
			_fork_linux_words 'open'
		fi
		_fork_linux_files
	fi
	return 0
}

complete -o filenames -F _fork_linux fork-linux
complete -o filenames -F _fork_linux_fork fork
