#!/usr/bin/env bash
# build-dev.sh - developer build of the Windows side of the Fork for Linux (unofficial)
# git bridge: fl-shim.exe and fl-launch.exe into build-bridge/dev/ (gitignored).
#
# usage: bridge/win/build-dev.sh
# (also builds the test-only build-bridge/dev/tests/fl-testdrv.exe for the Wine tier)
#
# On the host it re-runs itself inside fork-linux-ci-bridge:26.04
# (docker/Dockerfile.ci.bridge, built on demand) as the calling user; inside the
# container (--inside) it compiles bridge/common/*.c and bridge/win/*.c with the
# release flags of the meson build, embeds res/app.manifest + VERSIONINFO, and
# prints the sha256 of each output. The version comes from the repository's VERSION
# file through a generated fl_version.h (never a hard-coded literal).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/../.." && pwd)"
IMAGE="${FL_BRIDGE_IMAGE:-fork-linux-ci-bridge:26.04}"

if [[ "${1:-}" != "--inside" ]]; then
  if ! docker image inspect "${IMAGE}" > /dev/null 2>&1; then
    DOCKER_BUILDKIT=1 docker build -f "${ROOT}/docker/Dockerfile.ci.bridge" -t "${IMAGE}" "${ROOT}/docker"
  fi
  exec docker run --rm -u "$(id -u):$(id -g)" -v "${ROOT}:/src" -w /src "${IMAGE}" \
    bridge/win/build-dev.sh --inside
fi

OUT="${ROOT}/build-bridge/dev"
OBJ="${OUT}/obj"
COMMON="${ROOT}/bridge/common"
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1767225600}"

CC="x86_64-w64-mingw32-gcc"
WINDRES="x86_64-w64-mingw32-windres"
CFLAGS=(-std=c11 -O2 -municode -mwindows -DUNICODE -D_UNICODE -D_WIN32_WINNT=0x0601
  -Wall -Wextra -Werror -ffunction-sections -fdata-sections -fno-ident)
# Extra warnings for the Windows-side sources (bridge/common has its own gates).
WIN_CFLAGS=(-Wconversion -Wsign-conversion -Wshadow -Wstrict-prototypes -Wmissing-prototypes)
LDFLAGS=(-municode -mwindows -static -static-libgcc -s "-Wl,--gc-sections,--no-insert-timestamp,--build-id=none")
LIBS=(-lws2_32 -lbcrypt)

die() {
  echo "build-dev.sh: $*" >&2
  exit 1
}

command -v "${CC}" > /dev/null 2>&1 || die "${CC} not found"
command -v "${WINDRES}" > /dev/null 2>&1 || die "${WINDRES} not found"
[[ -d "${COMMON}" ]] || die "bridge/common is missing (the frozen C contract)"
mapfile -t COMMON_SRC < <(find "${COMMON}" -maxdepth 1 -name '*.c' | LC_ALL=C sort)
((${#COMMON_SRC[@]} > 0)) || die "no sources in bridge/common"

VERSION_TEXT="$(tr -d '[:space:]' < "${ROOT}/VERSION")"
[[ "${VERSION_TEXT}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] || die "VERSION is not N.N.N: '${VERSION_TEXT}'"

rm -rf "${OBJ}"
mkdir -p "${OBJ}"
cat > "${OBJ}/fl_version.h" << EOF
/* Generated by bridge/win/build-dev.sh from VERSION; do not edit. */
#define FL_VERSION_MAJOR ${BASH_REMATCH[1]}
#define FL_VERSION_MINOR ${BASH_REMATCH[2]}
#define FL_VERSION_PATCH ${BASH_REMATCH[3]}
#define FL_VERSION_STR "${VERSION_TEXT}"
EOF

INC=(-I "${COMMON}" -I "${HERE}")
COMMON_OBJ=()
for src in "${COMMON_SRC[@]}"; do
  o="${OBJ}/common_$(basename "${src}" .c).o"
  "${CC}" "${CFLAGS[@]}" "${INC[@]}" -c -o "${o}" "${src}"
  COMMON_OBJ+=("${o}")
done
for src in fl_win fl_shim fl_launch; do
  "${CC}" "${CFLAGS[@]}" "${WIN_CFLAGS[@]}" "${INC[@]}" -c -o "${OBJ}/${src}.o" "${HERE}/${src}.c"
done
for rc in fl_shim fl_launch; do
  "${WINDRES}" --input-format=rc --output-format=coff -I "${OBJ}" -I "${HERE}/res" \
    -i "${HERE}/res/${rc}.rc" -o "${OBJ}/${rc}_res.o"
done

"${CC}" "${LDFLAGS[@]}" -o "${OUT}/fl-shim.exe" \
  "${OBJ}/fl_shim.o" "${OBJ}/fl_win.o" "${OBJ}/fl_shim_res.o" "${COMMON_OBJ[@]}" "${LIBS[@]}"
"${CC}" "${LDFLAGS[@]}" -o "${OUT}/fl-launch.exe" \
  "${OBJ}/fl_launch.o" "${OBJ}/fl_win.o" "${OBJ}/fl_launch_res.o" "${COMMON_OBJ[@]}" "${LIBS[@]}"

# Test-only driver for tests/bridge/test_shims_wine.py (console subsystem; never shipped).
mkdir -p "${OUT}/tests"
"${CC}" -std=c11 -O2 -municode -DUNICODE -D_UNICODE -D_WIN32_WINNT=0x0601 -Wall -Wextra -Werror \
  "${WIN_CFLAGS[@]}" -static -static-libgcc -s -o "${OUT}/tests/fl-testdrv.exe" "${HERE}/tests/fl_testdrv.c"

(
  cd "${OUT}"
  for f in fl-shim.exe fl-launch.exe; do
    printf '%-14s %s\n' "${f}" "$(file -b "${f}" | cut -c1-90)"
  done
  sha256sum fl-shim.exe fl-launch.exe | tee SHA256SUMS
)
echo "build-dev.sh: OK -> ${OUT}"
