"""Give Fork's bundled (Windows) git a translated copy of the user's Linux git configuration.

The host ``~/.config/git/config`` and ``~/.gitconfig`` are translated into
``C:\\users\\<u>\\.config\\fork-linux\\gitconfig-host``: absolute paths become
``Z:/…`` (``includeIf "gitdir:…"`` conditions and path-valued keys), and
settings that would run a Linux program under Wine (credential helpers,
editors, gpg, an ``ssh`` command given by absolute path) are commented out
with the reason. A small managed ``[include]`` block at the top of the Wine
user's own ``.gitconfig`` pulls the translation in; everything else in that
file (Fork writes ``user.name`` / ``user.email`` there on first run) is kept,
and because it comes after the include it wins.

The overlay ends with a block fork-linux always adds (it comes last, so it
wins over the translated host values): ``url.<Z:>.insteadOf`` rewrites that
turn remotes written by Linux git (``file:///home/…``, ``/home/…``) into paths
msys git can open, and ``credential.credentialStore = dpapi`` (the Windows
credential store Git Credential Manager uses by default fails under Wine).

:func:`env_overrides` turns ``[git] env_overrides`` into ``GIT_CONFIG_COUNT``
/ ``GIT_CONFIG_KEY_n`` / ``GIT_CONFIG_VALUE_n`` for the launcher; with a host
git >= 2.48 (:func:`host_git_version`) it adds ``worktree.useRelativePaths``.
"""

from __future__ import annotations

import json
import logging
import os
import re
import shlex
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import fsutil
from .errors import ForkLinuxError, NotSetUpError, UsageError
from .pathmap import PathMap
from .paths import Paths
from .procrun import Runner

log = logging.getLogger(__name__)

MARK_BEGIN = "# BEGIN fork-linux (managed; do not edit)"
MARK_END = "# END fork-linux"
OVERLAY_REL = (".config", "fork-linux", "gitconfig-host")
OVERLAY_INCLUDE = "~/.config/fork-linux/gitconfig-host"
BLOCK_BODY = ("[include]", f"\tpath = {OVERLAY_INCLUDE}")
HEADER = (
    "# GENERATED by fork-linux from ~/.config/git/config and ~/.gitconfig — do not edit;\n"
    "# edit the originals instead: this file is rebuilt before Fork starts.\n"
)
DROP_PREFIX = "# fork-linux: dropped"
FILE_MODE = 0o600
ENCODING = "utf-8"
ERRORS = "surrogateescape"

# section.key (lower case) whose value is a path; "includeif.*" covers every condition.
PATH_KEYS = frozenset(
    {
        "include.path",
        "includeif.*.path",
        "core.excludesfile",
        "core.hookspath",
        "core.attributesfile",
        "commit.template",
        "init.templatedir",
    }
)
# section[.*].key (lower case) -> why it cannot work under Wine.
DROPPED_KEYS = {
    "credential.helper": "Linux credential helpers cannot run under Wine",
    "credential.*.helper": "Linux credential helpers cannot run under Wine",
    "core.editor": "a Linux editor cannot run under Wine",
    "sequence.editor": "a Linux editor cannot run under Wine",
    "gpg.program": "the Linux gpg cannot run under Wine",
    "gpg.*.program": "the Linux gpg cannot run under Wine",
}
SSH_COMMAND = "core.sshcommand"
SSH_COMMAND_REASON = "it names a Linux program by absolute path"
OPTIONAL_PREFIX = ":(optional)"
# Include paths that git resolves against the directory of the file that names them.
INCLUDE_KEYS = frozenset({"include.path", "includeif.*.path"})
# The host files git reads, in order (later values win).
HOST_FILES = ((".config", "git", "config"), (".gitconfig",))
# Bump when the generated overlay changes, so existing installs regenerate it.
OVERLAY_REVISION = 2
MANAGED_HEADER = "# fork-linux: added for Wine (comes last, so it wins over the values above)\n"
# Top-level host directories whose Linux paths in remote URLs are rewritten to Z: paths.
REWRITE_TOPS = ("home", "mnt", "media", "srv", "opt", "tmp", "var", "run")
CREDENTIAL_STORE = "dpapi"
# worktree.useRelativePaths sets extensions.relativeWorktrees, which git before 2.48 refuses.
RELATIVE_WORKTREES_KEY = "worktree.useRelativePaths"
RELATIVE_WORKTREES_MIN = (2, 48)
GIT_VERSION_CACHE = "host-git-version.json"
GIT_VERSION_TIMEOUT = 5.0
_GIT_VERSION_RE = re.compile(r"git version ([0-9]+)\.([0-9]+)(?:\.([0-9]+))?")

_HEADER_RE = re.compile(r'^(\s*)\[\s*([A-Za-z0-9.-]+)(?:\s+"((?:[^"\\\n]|\\.)*)")?\s*\]')
_ENTRY_RE = re.compile(r"^(\s*)([A-Za-z][A-Za-z0-9-]*)\s*(=?)(.*)$", re.DOTALL)
_GITDIR_RE = re.compile(r"^(gitdir(?:/i)?:)(/.*)$", re.DOTALL)
_GLOB_CHARS = re.compile(r"[*?\[\\]")
_ESCAPES = {"t": "\t", "b": "\b", "n": "\n", "\\": "\\", '"': '"'}
_NEEDS_QUOTES = re.compile(r'^\s|\s$|[#;"\\\n\t\b]')
# isspace() in the C locale, as git uses it.
_SPACES = " \t\r\v\f"


@dataclass
class _Section:
    """The section currently in effect while reading a file."""

    name: str = ""
    sub: str | None = None

    def key(self, name: str) -> str:
        """``section.key`` (or ``section.*.key`` with a subsection), lower case."""
        middle = "" if self.sub is None else "*."
        return f"{self.name.lower()}.{middle}{name.lower()}"

    def label(self, name: str) -> str:
        """``section.sub.key`` as git shows it, for notes."""
        middle = "" if self.sub is None else f"{self.sub}."
        return f"{self.name.lower()}.{middle}{name.lower()}"


def _read(path: Path) -> str:
    """Text of ``path`` (undecodable bytes preserved), or ``""`` when it does not exist."""
    try:
        return path.read_bytes().decode(ENCODING, ERRORS)
    except FileNotFoundError:
        return ""
    except OSError as exc:
        raise ForkLinuxError(f"cannot read {path}: {exc.strerror or exc}") from exc


def _write(path: Path, text: str, *, mode: int = FILE_MODE) -> None:
    """Atomically write ``text`` (undecodable bytes restored)."""
    fsutil.atomic_write(path, text.encode(ENCODING, ERRORS), mode=mode)


def host_config_text(host_home: Path) -> str:
    """The user's global git configuration: ``~/.config/git/config`` then ``~/.gitconfig``.

    Git reads them in this order (later values win), so they are
    concatenated the same way. Missing files contribute nothing.
    """
    return "".join(_from_header(rel, text) for rel, text in _host_files(host_home))


def _host_files(host_home: Path) -> list[tuple[tuple[str, ...], str]]:
    """``(relative path, text)`` of every non-empty host git config file, in git's order."""
    files = []
    for rel in HOST_FILES:
        text = _read(Path(host_home).joinpath(*rel))
        if text:
            files.append((rel, text))
    return files


def _from_header(rel: tuple[str, ...], text: str) -> str:
    """``text`` under a ``# from ~/<rel>`` comment, ending with a newline."""
    return f"# from ~/{'/'.join(rel)}\n{text}" + ("" if text.endswith("\n") else "\n")


def _parse_value(lines: list[str], index: int, rest: str) -> tuple[str | None, int]:
    """Git's value parser over ``rest`` (and continuation lines after ``lines[index]``).

    Returns ``(value, last_index)``; ``value`` is ``None`` when git would
    reject the value (open quote at the end of the line, unknown escape).
    """
    out: list[str] = []
    quote = False
    comment = False
    trim_len = 0
    text = rest
    pos = 0
    while True:
        if pos >= len(text) or text[pos] == "\n":
            if quote:
                return None, index
            return ("".join(out[:trim_len]) if trim_len else "".join(out)), index
        char = text[pos]
        pos += 1
        if comment:
            continue
        if char in _SPACES and not quote:
            if not trim_len:
                trim_len = len(out)
            if out:
                out.append(char)
            continue
        if not quote and char in "#;":
            comment = True
            continue
        trim_len = 0
        if char == "\\":
            nxt = text[pos] if pos < len(text) else "\n"
            pos += 1
            if nxt == "\n":
                if index + 1 >= len(lines):
                    return "".join(out), index
                index += 1
                text, pos = lines[index], 0
                continue
            if nxt not in _ESCAPES:
                return None, index
            out.append(_ESCAPES[nxt])
            continue
        if char == '"':
            quote = not quote
            continue
        out.append(char)


def _quote(value: str) -> str:
    """``value`` written so git reads it back unchanged."""
    if not value or not _NEEDS_QUOTES.search(value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n").replace("\t", "\\t").replace("\b", "\\b")
    return f'"{escaped}"'


def _quote_sub(sub: str) -> str:
    """A subsection name in its quoted header form."""
    return '"' + sub.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _unix_to_slash(path: str, pathmap: PathMap) -> str:
    """``/a/b`` -> ``Z:/a/b`` (forward slashes); :class:`UsageError` when unmapped."""
    return pathmap.unix_to_win(path).replace("\\", "/")


def _expand_home(path: str, home: Path | None) -> str:
    """``~`` / ``~/x`` against the host ``home`` (unchanged without one)."""
    if home is not None and (path == "~" or path.startswith("~/")):
        return str(home).rstrip("/") + path[1:]
    return path


def _translate_path(value: str, pathmap: PathMap, home: Path | None = None, base: Path | None = None) -> str:
    """Translate a Linux path value to ``Z:/…``; special values are kept.

    ``~/`` is expanded against the host ``home`` and a relative path joined
    to ``base`` when they are given (kept as they are otherwise): under Wine
    ``~`` is the Windows user directory, not the Linux home.
    """
    prefix = OPTIONAL_PREFIX if value.startswith(OPTIONAL_PREFIX) else ""
    path = _expand_home(value[len(prefix):], home)
    if base is not None and path and not path.startswith(("/", "~")):
        path = str(base / path)
    if not path.startswith("/"):
        return value
    translated = _unix_to_slash(path, pathmap)
    if path.endswith("/") and not translated.endswith("/"):
        translated += "/"
    return prefix + translated


def _translate_gitdir(condition: str, pathmap: PathMap, home: Path | None = None) -> str:
    """``gitdir:/x/**/y/`` -> ``gitdir:Z:/x/**/y/``: the literal leading part is mapped.

    With the host ``home``, ``gitdir:~/x/`` is mapped too (repositories are
    seen under ``Z:``, never under the Windows ``~``).
    """
    keyword, sep, pattern = condition.partition(":")
    if sep and keyword.lower() in ("gitdir", "gitdir/i"):
        condition = keyword + sep + _expand_home(pattern, home)
    match = _GITDIR_RE.match(condition)
    if match is None:
        return condition
    keyword, pattern = match.groups()
    trailing = pattern.endswith("/")
    parts = pattern.rstrip("/").split("/")[1:]
    split = next((i for i, part in enumerate(parts) if _GLOB_CHARS.search(part)), len(parts))
    mapped = _unix_to_slash("/" + "/".join(parts[:split]), pathmap)
    rest = parts[split:]
    out = mapped.rstrip("/") + "/" + "/".join(rest) if rest else mapped
    if trailing and not out.endswith("/"):
        out += "/"
    return keyword + out


def _ssh_command_is_linux(value: str) -> bool:
    """True when the ``core.sshCommand`` value names an absolute Linux path."""
    try:
        words = shlex.split(value)
    except ValueError:
        words = value.split()
    return any(word.startswith("/") for word in words)


def _drop_reason(key: str, value: str | None) -> str | None:
    """Why the entry ``key`` (lower-case ``section[.*].name``) must be dropped, or ``None``."""
    if key in DROPPED_KEYS:
        return DROPPED_KEYS[key]
    if key == SSH_COMMAND and value is not None and _ssh_command_is_linux(value):
        return SSH_COMMAND_REASON
    return None


class _Translator:
    """One pass over a git config text."""

    def __init__(self, text: str, pathmap: PathMap, home: Path | None = None, base: Path | None = None) -> None:
        self.lines = _lines(text)
        self.pathmap = pathmap
        self.home = home
        self.base = base
        self.section = _Section()
        self.out: list[str] = []
        self.notes: list[str] = []

    def run(self) -> tuple[str, list[str]]:
        index = 0
        while index < len(self.lines):
            index = self._line(self.lines[index], index) + 1
        text = "\n".join(self.out)
        return (text + "\n" if text else text), self.notes

    def _line(self, line: str, index: int) -> int:
        """Translate the logical line starting at ``lines[index]``; return its last index."""
        stripped = line.strip()
        if not stripped or stripped[0] in "#;":
            self.out.append(line)
            return index
        header = _HEADER_RE.match(line)
        if header is not None:
            return self._header(line, header, index)
        return self._entry(line, index)

    def _header(self, line: str, match: re.Match[str], index: int) -> int:
        indent, name, sub = match.groups()
        if sub is not None:
            sub = re.sub(r"\\(.)", r"\1", sub)
        elif "." in name:
            name, _dot, legacy = name.partition(".")
            sub = legacy.lower()
        self.section = _Section(name, sub)
        new_sub = sub
        if name.lower() == "includeif" and sub is not None:
            new_sub = self._mapped(sub, f"includeIf condition {sub!r}", lambda: _translate_gitdir(sub, self.pathmap, self.home))
        if new_sub == sub:
            self.out.append(line[: match.end()])
        else:
            self.out.append(f"{indent}[{name} {_quote_sub(new_sub)}]")
        rest = line[match.end():]
        if not rest.strip():
            return index
        # "[section] key = value" on one line: continue with the entry part.
        self.lines[index] = indent + "\t" + rest.strip()
        return self._line(self.lines[index], index)

    def _entry(self, line: str, index: int) -> int:
        match = _ENTRY_RE.match(line)
        if match is None:
            self.out.append(line)
            return index
        indent, name, equals, rest = match.groups()
        if equals:
            value, last = _parse_value(self.lines, index, rest)
        else:
            value, last = (None if rest.strip() and rest.strip()[0] not in "#;" else ""), index
        physical = self.lines[index : last + 1]
        if value is None:
            self.out.extend(physical)
            return last
        key = self.section.key(name)
        reason = _drop_reason(key, value if equals else None)
        if reason is not None:
            self.out.extend(f"{DROP_PREFIX} ({reason}): {raw}" for raw in physical)
            self.notes.append(f"{self.section.label(name)}: dropped ({reason})")
            return last
        if key in PATH_KEYS and equals:
            label = f"{self.section.label(name)} = {value!r}"
            base = self.base if key in INCLUDE_KEYS else None
            new = self._mapped(value, label, lambda: _translate_path(value, self.pathmap, self.home, base))
            if new != value:
                self.out.append(f"{indent}{name} = {_quote(new)}")
                return last
        self.out.extend(physical)
        return last

    def _mapped(self, original: str, label: str, convert: Callable[[], str]) -> str:
        """``convert()``, or ``original`` (with a note) when the path is not reachable from Wine."""
        try:
            return convert()
        except UsageError as exc:
            self.notes.append(f"{label}: kept unchanged ({exc.message})")
            return original


def translate(
    text: str, pathmap: PathMap, *, home: Path | None = None, base: Path | None = None
) -> tuple[str, list[str]]:
    """Translate a git config text for Fork's Windows git.

    Returns ``(text, notes)``: the translated configuration and one note per
    dropped entry or untranslatable path. Comments, layout and every other
    entry are kept as they are; entries git itself would reject are copied
    unchanged. ``~/`` paths are kept unless the host ``home`` is given;
    relative include paths are kept unless ``base`` (the directory of the
    file the text comes from) is given.
    """
    return _Translator(text, pathmap, home, base).run()


def overlay_path(paths: Paths, user: str) -> Path:
    """``C:\\users\\<u>\\.config\\fork-linux\\gitconfig-host``."""
    return paths.wine_user_dir(user).joinpath(*OVERLAY_REL)


def _lines(text: str) -> list[str]:
    """``text`` split at ``\n`` only (``\r\n`` accepted); no empty last line."""
    lines = text.replace("\r\n", "\n").split("\n")
    return lines[:-1] if lines[-1] == "" else lines


def _newline(text: str) -> str:
    """The line ending ``text`` uses (``\\r\\n`` when Windows-style)."""
    return "\r\n" if "\r\n" in text else "\n"


def _strip_block(text: str) -> str:
    """``text`` without any managed block (a block whose END marker is lost loses its body too)."""
    lines = [part for part in re.split(r"(?<=\n)", text) if part]
    out: list[str] = []
    index = 0
    while index < len(lines):
        if lines[index].strip() != MARK_BEGIN:
            out.append(lines[index])
            index += 1
            continue
        end = next((j for j in range(index + 1, len(lines)) if lines[j].strip() == MARK_END), None)
        if end is not None:
            index = end + 1
            continue
        index += 1
        for body in BLOCK_BODY:
            if index < len(lines) and lines[index].strip() == body.strip():
                index += 1
    return "".join(out)


def ensure_block(text: str) -> str:
    """``text`` with exactly one managed ``[include]`` block, at the very top."""
    newline = _newline(text)
    block = newline.join((MARK_BEGIN, *BLOCK_BODY, MARK_END)) + newline
    return block + _strip_block(text)


def _wine_user_dir(paths: Paths, user: str) -> Path:
    """The Wine user directory; :class:`NotSetUpError` when the prefix has none."""
    user_dir = paths.wine_user_dir(user)
    if not user_dir.is_dir():
        raise NotSetUpError(
            f"the Wine prefix has no user directory {user_dir}",
            hint="run 'fork-linux setup' first",
        )
    return user_dir


def _replace(path: Path, text: str) -> bool:
    """Write ``text`` to ``path`` unless it already holds it, keeping its mode; True if written.

    A symbolic link is replaced by a regular file (its target is never written).
    """
    current: str | None = None
    mode = FILE_MODE
    if path.exists() and not path.is_symlink():
        current = _read(path)
        mode = path.stat().st_mode & 0o777
    if current == text:
        return False
    _write(path, text, mode=mode)
    return True


def rewrite_tops(host_root: Path = Path("/")) -> list[str]:
    """The :data:`REWRITE_TOPS` that exist as directories under ``host_root``."""
    return [top for top in REWRITE_TOPS if (Path(host_root) / top).is_dir()]


def managed_text(pathmap: PathMap, tops: list[str]) -> str:
    """The block fork-linux adds at the end of the overlay (remote rewrites, credential store).

    ``[url "file:///Z:/home/"] insteadOf = file:///home/`` and
    ``[url "Z:/home/"] insteadOf = /home/`` for each top-level directory in
    ``tops`` that Wine can reach: msys git would otherwise look for
    ``/home/…`` under its own installation directory.
    """
    lines = [MANAGED_HEADER.rstrip("\n")]
    for top in tops:
        try:
            drive = _unix_to_slash("/" + top, pathmap).rstrip("/") + "/"
        except UsageError:
            continue
        lines += [
            f"[url {_quote_sub('file:///' + drive)}]",
            f"\tinsteadOf = file:///{top}/",
            f"[url {_quote_sub(drive)}]",
            f"\tinsteadOf = /{top}/",
        ]
    lines += ["[credential]", f"\tcredentialStore = {CREDENTIAL_STORE}"]
    return "\n".join(lines) + "\n"


def sync(
    paths: Paths, user: str, host_home: Path, pathmap: PathMap, *, host_root: Path = Path("/")
) -> list[Path]:
    """Write the translated host configuration and the managed include; return the files changed.

    Writes ``<wine user>/.config/fork-linux/gitconfig-host`` (the translated
    host files, then :func:`managed_text`) and makes sure the managed
    ``[include]`` block is the first thing in ``<wine user>/.gitconfig``,
    keeping the rest of that file as it is.
    """
    user_dir = _wine_user_dir(paths, user)
    home = Path(host_home)
    notes: list[str] = []
    parts: list[str] = []
    # Each file on its own: sections do not carry over and relative includes are per file.
    for rel, text in _host_files(home):
        part, part_notes = translate(text, pathmap, home=home, base=home.joinpath(*rel).parent)
        parts.append(_from_header(rel, part))
        notes.extend(part_notes)
    translated = "".join(parts) + managed_text(pathmap, rewrite_tops(host_root))
    note_lines = "".join(f"# note: {note}\n" for note in notes)
    changed = []
    overlay = overlay_path(paths, user)
    if _replace(overlay, HEADER + note_lines + translated):
        changed.append(overlay)
    gitconfig = user_dir / ".gitconfig"
    # A .gitconfig linked to the host's would hand Fork untranslated paths: replace the link.
    base = "" if gitconfig.is_symlink() else _read(gitconfig)
    if _replace(gitconfig, ensure_block(base)):
        changed.append(gitconfig)
    return changed


def remove(paths: Paths, user: str) -> list[Path]:
    """Undo :func:`sync`: drop the managed block and our generated overlay; return the files changed."""
    user_dir = paths.wine_user_dir(user)
    changed = []
    gitconfig = user_dir / ".gitconfig"
    text = _read(gitconfig)
    stripped = _strip_block(text)
    if stripped != text:
        _write(gitconfig, stripped, mode=gitconfig.stat().st_mode & 0o777)
        changed.append(gitconfig)
    overlay = overlay_path(paths, user)
    if _read(overlay).startswith(HEADER):
        overlay.unlink()
        changed.append(overlay)
    return changed


def _parse_git_version(text: str) -> tuple[int, int, int] | None:
    """``(2, 53, 0)`` from ``git version 2.53.0``, or None."""
    match = _GIT_VERSION_RE.search(text)
    if match is None:
        return None
    return int(match.group(1)), int(match.group(2)), int(match.group(3) or 0)


def _read_cache(path: Path) -> dict[str, Any]:
    """The cached probe (``{}`` when missing or unusable)."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def host_git_version(runner: Runner, env: Mapping[str, str], cache_dir: Path) -> tuple[int, int, int] | None:
    """The host's ``git --version`` (None without git), cached by the binary's path, size and mtime.

    The cache file lives in ``cache_dir``; the probe runs again only when the
    git found on ``PATH`` changed. A failing probe counts as "no git".
    """
    git = runner.which("git", env.get("PATH"))
    if git is None:
        return None
    try:
        info = os.stat(git)
    except OSError:
        return None
    key = [os.path.realpath(git), info.st_size, info.st_mtime_ns]
    cache = Path(cache_dir) / GIT_VERSION_CACHE
    cached = _read_cache(cache)
    version = cached.get("version")
    if cached.get("key") == key and isinstance(version, list) and len(version) == 3:
        return int(version[0]), int(version[1]), int(version[2])
    try:
        completed = runner.run([git, "--version"], env=dict(env), timeout=GIT_VERSION_TIMEOUT)
    except ForkLinuxError:
        return None
    parsed = _parse_git_version(completed.stdout) if completed.ok else None
    if parsed is not None:
        try:
            fsutil.atomic_write(cache, json.dumps({"key": key, "version": list(parsed)}) + "\n")
        except OSError:
            log.debug("cannot cache the git version in %s", cache, exc_info=True)
    return parsed


def env_overrides(config: Any, *, git_version: tuple[int, ...] | None = None) -> dict[str, str]:
    """``GIT_CONFIG_COUNT`` / ``GIT_CONFIG_KEY_n`` / ``GIT_CONFIG_VALUE_n`` for Fork's git.

    The pairs come from ``[git] env_overrides`` (``key=value, key=value``);
    ``safe.directory=*`` is added when ``[git] safe_directory_all`` is true,
    and ``worktree.useRelativePaths=true`` when the host ``git_version`` is
    at least 2.48 (so native git can use worktrees Fork creates) and the user
    did not set that key. An empty result means no override at all.
    """
    pairs: list[tuple[str, str]] = []
    for item in config.getlist("git", "env_overrides"):
        key, sep, value = item.partition("=")
        key = key.strip()
        if not sep or not key or "." not in key.strip(".") or any(ch.isspace() for ch in key):
            raise UsageError(
                f"invalid git.env_overrides entry {item!r}: expected section.key=value",
                hint="for example: fork-linux config set git.env_overrides 'core.filemode=false, core.autocrlf=false'",
            )
        pairs.append((key, value.strip()))
    if config.getbool("git", "safe_directory_all"):
        pairs.append(("safe.directory", "*"))
    named = {key.lower() for key, _value in pairs}
    if (
        git_version is not None
        and tuple(git_version[:2]) >= RELATIVE_WORKTREES_MIN
        and RELATIVE_WORKTREES_KEY.lower() not in named
    ):
        pairs.append((RELATIVE_WORKTREES_KEY, "true"))
    if not pairs:
        return {}
    env = {"GIT_CONFIG_COUNT": str(len(pairs))}
    for number, (key, value) in enumerate(pairs):
        env[f"GIT_CONFIG_KEY_{number}"] = key
        env[f"GIT_CONFIG_VALUE_{number}"] = value
    return env
