"""Share the user's ``~/.ssh`` keys and config with Fork's bundled (msys) ssh.

The Wine side ``C:\\users\\<u>\\.ssh`` is a real ``0700`` directory (never a
link to ``~/.ssh``): private keys are symlinked into it (or copied ``0600``),
``known_hosts`` is symlinked so host keys accepted in Fork reach the Linux
side, and ``config`` is a translated copy of ``~/.ssh/config``: ``Include``
files are inlined, key paths become ``~/.ssh/<name>`` (msys resolves ``~`` to
the Wine user directory) or ``/z/<path>``, and directives that cannot work
under Wine (agent sockets, connection sharing, Linux commands) are commented
out with the reason. Files we manage are listed in a small manifest, so a key
removed from ``~/.ssh`` disappears from the prefix too, and a key the user
created inside Wine is never overwritten.
"""

from __future__ import annotations

import contextlib
import glob
import json
import logging
import os
import re
import shlex
import stat
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import fsutil
from .errors import ForkLinuxError, NotSetUpError, UsageError
from .paths import Paths

log = logging.getLogger(__name__)

MODES = ("link", "copy")
HEADER = "# GENERATED by fork-linux from ~/.ssh/config — edit the original, then run: fork-linux ssh sync"
DROP_PREFIX = "# fork-linux: dropped"
MANIFEST = ".fork-linux-managed.json"
CONFIG_BACKUP = "config.fork-linux-backup"
DIR_MODE = 0o700
PRIVATE_MODE = 0o600
PUBLIC_MODE = 0o644
MAX_INCLUDE_DEPTH = 16
MSYS_DRIVE = "/z"

_NO_SOCKETS = "connection sharing needs Unix sockets that Wine's ssh cannot use"
# Directives commented out, with the reason shown in the generated file.
DROPPED = {
    "identityagent": "the agent socket of the Linux session is not reachable from Wine",
    "usekeychain": "macOS only",
    "controlmaster": _NO_SOCKETS,
    "controlpath": _NO_SOCKETS,
    "controlpersist": _NO_SOCKETS,
    "knownhostscommand": "it runs a Linux command",
    "localcommand": "it runs a Linux command",
    "pkcs11provider": "it loads a Linux library",
    "securitykeyprovider": "it loads a Linux library",
}
MATCH_EXEC_REASON = "Match exec runs a Linux command"
IN_MATCH_EXEC_REASON = "inside a dropped Match exec block"
PROXY_REASON = "ProxyCommand runs a Linux command"
# Path-valued directives: single path, and lists of paths.
PATH_KEYWORDS = frozenset({"identityfile", "certificatefile"})
PATH_LIST_KEYWORDS = frozenset({"userknownhostsfile", "globalknownhostsfile"})
KEY_REFERENCES = frozenset({"identityfile", "certificatefile"})
UNTRANSLATED = frozenset({"none", "/dev/null"})

_KEYWORD_NAME_RE = re.compile(r"[A-Za-z][A-Za-z0-9]*")


@dataclass
class SyncReport:
    """What :func:`sync` did (or would do with ``dry_run``)."""

    linked: list[Path] = field(default_factory=list)
    copied: list[Path] = field(default_factory=list)
    dropped_directives: list[tuple[str, str]] = field(default_factory=list)
    config_path: Path | None = None
    skipped: list[Path] = field(default_factory=list)
    removed: list[Path] = field(default_factory=list)


def _split_args(value: str) -> list[str]:
    """ssh's argument splitting (quotes honoured); unbalanced quotes fall back to whitespace."""
    try:
        return shlex.split(value, comments=False, posix=True)
    except ValueError:
        return value.split()


def _quote_arg(arg: str) -> str:
    """One argument as ssh reads it back: double-quoted when it holds whitespace or quotes."""
    if arg and not any(ch.isspace() or ch in "\"'\\" for ch in arg):
        return arg
    return '"' + arg.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _is_ssh_proxy(value: str) -> bool:
    """True for ``ProxyCommand none`` and ``ProxyCommand ssh ...`` (msys has its own ssh)."""
    words = _split_args(value)
    return bool(words) and (words[0].lower() == "none" or os.path.basename(words[0]) == "ssh")


def _has_exec(value: str) -> bool:
    """True when a ``Match`` line uses the ``exec`` (or ``!exec``) criterion."""
    return any(word.lstrip("!").lower() == "exec" for word in _split_args(value))


def _directive_parts(line: str) -> tuple[str, str, str] | None:
    """``(indent, keyword, value)`` of a ``Keyword value`` / ``Keyword=value`` line (no line breaks).

    None for blank lines, comments and anything else that is not a directive.
    """
    body = line.lstrip()
    if not body or body.startswith("#"):
        return None
    name = _KEYWORD_NAME_RE.match(body)
    if name is None:
        return None
    after = body[name.end():]
    rest = after.lstrip()
    if rest.startswith("="):
        rest = rest[1:].lstrip()
    elif len(rest) == len(after):
        return None
    return line[: len(line) - len(body)], name.group(), rest.rstrip()


class _Translator:
    """Translates ``~/.ssh/config`` (and its Includes) for the msys ssh under Wine."""

    def __init__(self, host_home: Path) -> None:
        self.home = os.path.normpath(str(host_home))
        self.ssh_dir = os.path.join(self.home, ".ssh")
        self.out: list[str] = []
        self.dropped: list[tuple[str, str]] = []
        self.referenced: set[Path] = set()

    def expand(self, arg: str) -> str:
        """``~``, ``%d`` and ``${HOME}`` expanded against the host home; other text unchanged."""
        for token in ("~", "%d", "${HOME}"):
            if arg == token or arg.startswith(token + "/"):
                return self.home + arg[len(token):]
        return arg

    def path(self, arg: str) -> str:
        """Translate one path: under ``~/.ssh`` -> ``~/.ssh/<rel>``, other absolute -> ``/z/<abs>``."""
        if arg.lower() in UNTRANSLATED:
            return arg
        expanded = self.expand(arg)
        if not expanded.startswith("/"):
            return arg
        norm = os.path.normpath(expanded)
        if norm.startswith(self.ssh_dir + "/"):
            return "~/.ssh/" + norm[len(self.ssh_dir) + 1:]
        return MSYS_DRIVE + norm

    def drop(self, indent: str, line: str, reason: str) -> None:
        """Comment ``line`` out and record why."""
        self.out.append(f"{indent}{DROP_PREFIX} ({reason}): {line.strip()}")
        self.dropped.append((line.strip(), reason))

    def file(self, path: Path, stack: tuple[str, ...]) -> bool:
        """Translate ``path``; True when it contained a ``Host`` or ``Match`` line."""
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            self.out.append(f"# fork-linux: cannot read {path}: {exc.strerror or exc}")
            return False
        header: str | None = None
        dropping = False
        had_headers = False
        for line in text.splitlines():
            parts = _directive_parts(line)
            if parts is None:
                self.out.append(line)
                continue
            indent, keyword, value = parts
            lower = keyword.lower()
            if lower in ("host", "match"):
                had_headers = True
                dropping = self.block_header(line, indent, lower, value)
                if not dropping:
                    header = line.strip()
            elif dropping:
                self.drop(indent, line, IN_MATCH_EXEC_REASON)
            elif lower == "include":
                self.include(value, stack, header)
            else:
                self.directive(line, indent, keyword, value)
        return had_headers

    def block_header(self, line: str, indent: str, lower: str, value: str) -> bool:
        """Copy a ``Host`` / ``Match`` line; True (and dropped) for a ``Match exec`` block."""
        dropping = lower == "match" and _has_exec(value)
        if dropping:
            self.drop(indent, line, MATCH_EXEC_REASON)
        else:
            self.out.append(line)
        return dropping

    def include(self, value: str, stack: tuple[str, ...], header: str | None) -> None:
        """Inline every file an ``Include`` names (glob, relative to ``~/.ssh``), cycle-safe."""
        for pattern in _split_args(value):
            expanded = self.expand(pattern)
            if not expanded.startswith("/"):
                expanded = os.path.join(self.ssh_dir, expanded)
            matches = sorted(name for name in glob.glob(expanded) if os.path.isfile(name))
            if not matches:
                self.out.append(f"# fork-linux: Include {pattern} matched no file")
            for name in matches:
                self.include_file(name, stack, header)

    def include_file(self, name: str, stack: tuple[str, ...], header: str | None) -> None:
        """Inline one included file unless it would loop or nest too deep."""
        real = os.path.realpath(name)
        if real in stack or len(stack) >= MAX_INCLUDE_DEPTH:
            self.out.append(f"# fork-linux: skipped Include {name} (include loop or too deep)")
            return
        self.out.append(f"# fork-linux: begin Include {name}")
        changed_block = self.file(Path(name), (*stack, real))
        self.out.append(f"# fork-linux: end Include {name}")
        if changed_block:
            # The included file started its own Host/Match blocks: return to ours.
            self.out.append(header if header is not None else "Host *")

    def directive(self, line: str, indent: str, keyword: str, value: str) -> None:
        """Translate (or drop) one directive line."""
        lower = keyword.lower()
        if lower in DROPPED:
            self.drop(indent, line, DROPPED[lower])
            return
        if lower == "proxycommand" and not _is_ssh_proxy(value):
            self.drop(indent, line, PROXY_REASON)
            return
        if lower not in PATH_KEYWORDS and lower not in PATH_LIST_KEYWORDS:
            self.out.append(line)
            return
        args = _split_args(value)
        if lower in PATH_KEYWORDS:
            args = args[:1]
        translated = [self.path(arg) for arg in args]
        if lower in KEY_REFERENCES:
            for arg in args:
                expanded = self.expand(arg)
                if expanded.startswith("/"):
                    self.referenced.add(Path(os.path.normpath(expanded)))
        if translated == args:
            self.out.append(line)
            return
        self.out.append(f"{indent}{keyword} {' '.join(_quote_arg(arg) for arg in translated)}")


def translate_config(config: Path, host_home: Path) -> tuple[str, list[tuple[str, str]], set[Path]]:
    """Translate the ssh config file ``config``.

    Returns ``(text, dropped, referenced)``: the generated file (with the
    GENERATED header), the ``(directive, reason)`` pairs commented out, and
    the absolute host paths named by ``IdentityFile`` / ``CertificateFile``.
    """
    translator = _Translator(host_home)
    translator.file(Path(config), (os.path.realpath(config),))
    body = "\n".join(translator.out)
    text = f"{HEADER}\n# Source: {config}\n\n{body}\n"
    return text, translator.dropped, translator.referenced


def _id_keys(host_ssh: Path) -> dict[str, Path]:
    """The ``id_*`` private keys of ``host_ssh`` that have a ``.pub`` next to them."""
    if not host_ssh.is_dir():
        return {}
    return {
        entry.name: entry
        for entry in host_ssh.glob("id_*")
        if not entry.name.endswith(".pub") and entry.is_file() and entry.with_name(entry.name + ".pub").is_file()
    }


def _host_keys(host_ssh: Path, referenced: Iterable[Path]) -> list[tuple[str, Path]]:
    """``(relative name, host path)`` of every key file to share, sorted by name.

    ``id_*`` private keys that have a ``.pub``, the files the config names
    under ``~/.ssh``, and the ``.pub`` / ``-cert.pub`` next to each of them.
    """
    found = _id_keys(host_ssh)
    prefix = str(host_ssh) + "/"
    for path in referenced:
        if str(path).startswith(prefix) and path.is_file():
            found[str(path)[len(prefix):]] = path
    companions = {
        rel + suffix: path.with_name(path.name + suffix)
        for rel, path in found.items()
        for suffix in (".pub", "-cert.pub")
    }
    found.update({rel: path for rel, path in companions.items() if path.is_file()})
    return sorted(found.items())


def _read_manifest(wine_ssh: Path) -> set[str]:
    """Names (relative to the Wine ``.ssh``) that a previous sync created."""
    try:
        data = json.loads((wine_ssh / MANIFEST).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    files = data.get("files") if isinstance(data, dict) else None
    if not isinstance(files, list):
        return set()
    return {name for name in files if isinstance(name, str) and _safe_rel(name)}


def _safe_rel(name: str) -> bool:
    """True for a relative name that stays inside the directory."""
    parts = name.split("/")
    return bool(name) and not name.startswith("/") and ".." not in parts and "" not in parts


def _real_parents(root: Path, rel: str) -> bool:
    """True when no directory between ``root`` and ``root/rel`` is a symbolic link."""
    current = root
    for part in rel.split("/")[:-1]:
        current = current / part
        if current.is_symlink():
            return False
    return True


def _ensure_real_dir(directory: Path) -> None:
    """Make ``directory`` a real ``0700`` directory, replacing a symbolic link (never its target)."""
    if directory.is_symlink():
        directory.unlink()
    elif directory.exists() and not directory.is_dir():
        raise ForkLinuxError(
            f"{directory} exists but is not a directory",
            hint="move it out of the way, then run 'fork-linux ssh sync' again",
        )
    fsutil.ensure_dir(directory, DIR_MODE)


def _points_into(link: Path, root: str) -> bool:
    """True when the symbolic link ``link`` targets a path under ``root``."""
    target = os.path.normpath(os.path.join(str(link.parent), os.readlink(link)))
    return target.startswith(root + "/")


def _place_link(source: Path, dest: Path) -> None:
    """Atomically make ``dest`` a symbolic link to ``source``."""
    fsutil.ensure_dir(dest.parent, DIR_MODE)
    temp = dest.with_name(f".{dest.name}.fork-linux-tmp")
    with contextlib.suppress(FileNotFoundError):
        temp.unlink()
    os.symlink(str(source), temp)
    os.replace(temp, dest)


def _place_copy(source: Path, dest: Path) -> None:
    """Atomically copy ``source`` to ``dest`` (``0600``, or ``0644`` for public keys)."""
    fsutil.ensure_dir(dest.parent, DIR_MODE)
    mode = PUBLIC_MODE if dest.name.endswith(".pub") else PRIVATE_MODE
    fsutil.atomic_write(dest, source.read_bytes(), mode=mode)


class _Syncer:
    """State of one :func:`sync` run."""

    def __init__(self, wine_ssh: Path, host_ssh: Path, report: SyncReport, dry_run: bool) -> None:
        self.wine_ssh = wine_ssh
        self.host_root = os.path.normpath(str(host_ssh))
        self.report = report
        self.dry_run = dry_run
        self.previous = _read_manifest(wine_ssh)
        self.current: set[str] = set()

    def owned(self, rel: str) -> bool:
        """True when ``rel`` may be (re)written: absent, ours before, or a link into ``~/.ssh``."""
        dest = self.wine_ssh / rel
        if not _real_parents(self.wine_ssh, rel):
            return False
        if not os.path.lexists(dest) or rel in self.previous:
            return True
        return dest.is_symlink() and _points_into(dest, self.host_root)

    def place(self, rel: str, source: Path, *, link: bool) -> None:
        """Link or copy ``source`` to ``rel`` unless a foreign file is in the way."""
        dest = self.wine_ssh / rel
        if not self.owned(rel):
            log.warning("leaving %s alone: it was not created by fork-linux", dest)
            self.report.skipped.append(dest)
            return
        self.current.add(rel)
        if link:
            self.report.linked.append(dest)
            if not self.dry_run:
                _place_link(source, dest)
        else:
            self.report.copied.append(dest)
            if not self.dry_run:
                _place_copy(source, dest)

    def write_config(self, text: str) -> None:
        """Write the generated config; a hand-written one is moved to a backup first (never lost)."""
        dest = self.wine_ssh / "config"
        backup = self.wine_ssh / CONFIG_BACKUP
        foreign = dest.is_file() and not dest.is_symlink() and "config" not in self.previous and not _generated(dest)
        if foreign and os.path.lexists(backup):
            log.warning("leaving %s alone: it was not created by fork-linux and %s already exists", dest, backup)
            self.report.skipped.append(dest)
            return
        self.current.add("config")
        self.report.config_path = dest
        if self.dry_run:
            return
        if foreign:
            os.replace(dest, backup)
            log.warning("moved the hand-written %s to %s", dest, backup)
        fsutil.atomic_write(dest, text, mode=PRIVATE_MODE)

    def cleanup(self) -> None:
        """Remove what a previous sync created and this one did not."""
        for rel in sorted(self.previous - self.current):
            dest = self.wine_ssh / rel
            if not _real_parents(self.wine_ssh, rel) or not os.path.lexists(dest):
                continue
            if dest.is_dir() and not dest.is_symlink():
                continue
            if rel == "config" and not dest.is_symlink() and not _generated(dest):
                continue
            self.report.removed.append(dest)
            if not self.dry_run:
                dest.unlink()

    def save(self) -> None:
        """Record the names this sync manages."""
        if self.dry_run:
            return
        data = {"schema": 1, "files": sorted(self.current)}
        fsutil.atomic_write(self.wine_ssh / MANIFEST, json.dumps(data, indent=2) + "\n", mode=PRIVATE_MODE)


def _generated(path: Path) -> bool:
    """True when ``path`` starts with our GENERATED header."""
    try:
        with open(path, encoding="utf-8", errors="replace") as handle:
            return handle.readline().rstrip("\n") == HEADER
    except OSError:
        return False


def _wine_ssh_dir(paths: Paths, user: str) -> Path:
    """``C:\\users\\<u>\\.ssh``; :class:`NotSetUpError` when the prefix has no user directory."""
    user_dir = paths.wine_user_dir(user)
    if not user_dir.is_dir():
        raise NotSetUpError(
            f"the Wine prefix has no user directory {user_dir}",
            hint="run 'fork-linux setup' first",
        )
    return user_dir / ".ssh"


def sync(
    paths: Paths,
    user: str,
    host_home: Path,
    *,
    mode: str = "link",
    include_config: bool = True,
    dry_run: bool = False,
) -> SyncReport:
    """Share ``host_home/.ssh`` with the Wine user ``user`` (see the module docstring).

    ``mode`` is ``link`` (symbolic links) or ``copy`` (private copies);
    ``known_hosts`` is always linked. With ``dry_run`` nothing is written and
    the report says what would happen.
    """
    if mode not in MODES:
        raise UsageError(f"unknown ssh sync mode {mode!r}", hint="use link or copy")
    wine_ssh = _wine_ssh_dir(paths, user)
    host_ssh = Path(host_home) / ".ssh"
    report = SyncReport()
    config_text: str | None = None
    referenced: set[Path] = set()
    host_config = host_ssh / "config"
    if include_config and host_config.is_file():
        config_text, report.dropped_directives, referenced = translate_config(host_config, Path(host_home))
    if not dry_run:
        _ensure_real_dir(wine_ssh)
    syncer = _Syncer(wine_ssh, host_ssh, report, dry_run)
    for rel, source in _host_keys(host_ssh, referenced):
        syncer.place(rel, source, link=mode == "link")
    known_hosts = host_ssh / "known_hosts"
    if known_hosts.is_file():
        syncer.place("known_hosts", known_hosts, link=True)
    if config_text is not None:
        syncer.write_config(config_text)
    syncer.cleanup()
    syncer.save()
    return report


def _broken_links(directory: Path) -> list[str]:
    """Relative names of dangling symbolic links under ``directory``."""
    broken = []
    for dirpath, dirnames, filenames in os.walk(directory):
        for name in [*dirnames, *filenames]:
            path = Path(dirpath) / name
            if path.is_symlink() and not path.exists():
                broken.append(str(path.relative_to(directory)))
    return sorted(broken)


def _insecure(directory: Path, names: Iterable[str]) -> list[str]:
    """Managed private files (regular files, not ``.pub``) readable by group or others."""
    bad = []
    for rel in sorted(names):
        path = directory / rel
        if rel.endswith(".pub") or rel == "known_hosts" or path.is_symlink() or not path.is_file():
            continue
        if stat.S_IMODE(path.stat().st_mode) & 0o077:
            bad.append(rel)
    return bad


def _config_state(wine_config: Path, host_config: Path, host_home: Path) -> str:
    """``none``, ``missing``, ``current``, ``stale`` or ``foreign``."""
    if not os.path.lexists(wine_config):
        return "missing" if host_config.is_file() else "none"
    if not _generated(wine_config):
        return "foreign"
    if not host_config.is_file():
        return "stale"
    fresh, _dropped, _referenced = translate_config(host_config, host_home)
    current = wine_config.read_text(encoding="utf-8", errors="replace")
    return "current" if current == fresh else "stale"


def status(paths: Paths, user: str, host_home: Path) -> dict[str, Any]:
    """Health of the shared ssh setup (for ``ssh status`` and ``doctor``)."""
    wine_ssh = paths.wine_user_dir(user) / ".ssh"
    host_ssh = Path(host_home) / ".ssh"
    is_link = wine_ssh.is_symlink()
    is_dir = wine_ssh.is_dir() and not is_link
    mode = stat.S_IMODE(wine_ssh.stat().st_mode) if is_dir else None
    managed = sorted(_read_manifest(wine_ssh)) if is_dir else []
    insecure = _insecure(wine_ssh, managed) if is_dir else []
    config = _config_state(wine_ssh / "config", host_ssh / "config", Path(host_home)) if is_dir else "none"
    return {
        "host_dir": str(host_ssh),
        "host_present": host_ssh.is_dir(),
        "wine_dir": str(wine_ssh),
        "exists": is_dir or is_link,
        "is_symlink": is_link,
        "dir_ok": is_dir and mode == DIR_MODE,
        "mode": None if mode is None else f"{mode:04o}",
        "perms_ok": is_dir and mode == DIR_MODE and not insecure,
        "insecure_files": insecure,
        "managed": managed,
        "broken_links": _broken_links(wine_ssh) if is_dir else [],
        "config": config,
        "stale_config": config == "stale",
    }
