#!/usr/bin/env python3
"""Generate the installed data files of Fork for Linux (unofficial) from their single sources.

* ``desktop OUT``          the system menu entry, rendered from
  ``src/fork_linux/data/templates/io.github.ventura8.ForkLinux.desktop.in``
  exactly like the per-user one (``desktop_integration``), with ``Exec=fork-linux``;
* ``metainfo IN OUT``      the AppStream metainfo: ``@APP_ID@`` / ``@APP_NAME@`` and the
  ``@DESCRIPTION@`` paragraphs from ``credits.render_metainfo_paragraphs()``;
* ``fm-action KIND OUT``   a system-wide "Open in Fork" file-manager action
  (``nautilus``, ``nemo``, ``dolphin``, ``fma``) from the same templates;
* ``completions SHELL``    bash / zsh / fish completions generated from the argparse parser;
* ``man PAGE``             the ``fork-linux.1`` / ``fork.1`` manual pages, from the parser too;
* ``write`` / ``check``    regenerate (or verify, exit 1 on drift) the committed
  ``data/completions/*`` and ``data/man/*``.

Meson runs the first three at build time; the completions and manual pages are
committed (so the lint stage can run ``bash -n`` / ``zsh -n`` / ``fish -n`` on them) and
``tests/test_completions.py`` / ``tests/test_manpages.py`` fail when they drift.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
COMMITTED = {
    ("completions", "bash"): Path("data/completions/fork-linux.bash"),
    ("completions", "zsh"): Path("data/completions/_fork-linux"),
    ("completions", "fish"): Path("data/completions/fork-linux.fish"),
    ("man", "fork-linux"): Path("data/man/fork-linux.1"),
    ("man", "fork"): Path("data/man/fork.1"),
}
FM_KINDS = ("nautilus", "nemo", "dolphin", "fma")
SYSTEM_COMMAND = ["fork-linux"]
GENERATED_NOTE = "GENERATED by fork-linux desktop install; removed by fork-linux desktop remove."
SYSTEM_NOTE = "Installed system-wide by the fork-linux package (meson -Dfile_manager_actions=true)."
HEADER = "Generated by scripts/gen-data.py from the fork-linux argparse parser; do not edit."


def _import_package() -> None:
    """Make ``fork_linux`` importable from the source tree, with a stable help width."""
    os.environ["COLUMNS"] = "100"
    if str(SRC) not in sys.path:
        sys.path.insert(0, str(SRC))


# --------------------------------------------------------------------------- parser model


@dataclass
class Option:
    """One option of a command: its spellings, help and what its value completes to."""

    flags: list[str]
    help: str
    takes_value: bool
    choices: list[str] = field(default_factory=list)
    value_kind: str = ""  # "", "file" or "dir"
    metavar: str = ""


@dataclass
class Node:
    """A command (``()`` is the top level): options, subcommands and positionals."""

    path: tuple[str, ...]
    help: str
    options: list[Option]
    subcommands: list[tuple[str, str, Node]]  # (name, help, node); aliases repeat the node
    positionals: list[tuple[str, str, list[str]]]  # (metavar, help, choices)

    @property
    def key(self) -> str:
        return " ".join(self.path)


def _expand_help(action: argparse.Action) -> str:
    text = action.help or ""
    if text == argparse.SUPPRESS:
        return ""
    if "%(" in text:
        params = {k: v for k, v in vars(action).items() if v is not argparse.SUPPRESS}
        params.setdefault("prog", "fork-linux")
        text = text % params
    return " ".join(text.split())


def _value_info(action: argparse.Action) -> tuple[list[str], str]:
    """``(choices, kind)`` for an option or positional value."""
    if action.choices is not None:
        return [str(choice) for choice in action.choices], ""
    metavar = action.metavar if isinstance(action.metavar, str) else ""
    choices: list[str] = []
    kind = ""
    if metavar.startswith("{") and metavar.endswith("}"):
        for item in metavar[1:-1].split(","):
            if item.isupper():
                kind = "file"
            else:
                choices.append(item)
        return choices, kind
    if action.dest == "prefix":
        return [], "dir"
    if action.type is Path or metavar in {"PATH", "FILE"} or action.dest in {"paths", "file", "path"}:
        return [], "file"
    return [], ""


def _option(action: argparse.Action) -> Option:
    takes_value = action.nargs != 0
    choices, kind = _value_info(action) if takes_value else ([], "")
    if isinstance(action.metavar, str):
        metavar = action.metavar
    elif action.choices is not None:
        metavar = "{" + ",".join(str(choice) for choice in action.choices) + "}"
    else:
        metavar = action.dest.upper()
    return Option(list(action.option_strings), _expand_help(action), takes_value, choices, kind, metavar)


def build_tree(parser: argparse.ArgumentParser, path: tuple[str, ...] = (), help_text: str = "") -> Node:
    """The command tree of ``parser``."""
    options: list[Option] = []
    subcommands: list[tuple[str, str, Node]] = []
    positionals: list[tuple[str, str, list[str]]] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {choice.dest: _expand_help(choice) for choice in action._choices_actions}
            built: dict[int, Node] = {}
            for name, sub in action.choices.items():
                if id(sub) not in built:
                    built[id(sub)] = build_tree(sub, (*path, name), helps.get(name, ""))
                child = built[id(sub)]
                subcommands.append((name, child.help, child))
        elif action.option_strings:
            options.append(_option(action))
        else:
            choices, _kind = _value_info(action)
            metavar = action.metavar if isinstance(action.metavar, str) else action.dest
            positionals.append((metavar, _expand_help(action), choices))
    return Node(path, help_text, options, subcommands, positionals)


def load_tree() -> Node:
    """The fork-linux command tree."""
    _import_package()
    from fork_linux.cli import build_parser

    return build_tree(build_parser())


def walk(node: Node) -> list[Node]:
    """Every distinct node, depth first (aliases visited once, under their first name)."""
    seen: set[int] = set()
    out: list[Node] = []

    def visit(current: Node) -> None:
        if id(current) in seen:
            return
        seen.add(id(current))
        out.append(current)
        for _name, _help, child in current.subcommands:
            visit(child)

    visit(node)
    return out


def all_nodes(node: Node) -> list[Node]:
    """Every node including alias paths (``credits`` as well as ``about``)."""
    out = [node]
    for _name, _help, child in node.subcommands:
        out.extend(all_nodes(child))
    return out


def keyed_nodes(node: Node, prefix: tuple[str, ...] = ()) -> list[tuple[str, Node]]:
    """``(command words, node)`` for every way of naming a command, aliases included."""
    out = [(" ".join(prefix), node)]
    for name, _help, child in node.subcommands:
        out.extend(keyed_nodes(child, (*prefix, name)))
    return out


def global_flags(tree: Node) -> list[str]:
    """Option spellings every subcommand accepts (the top-level global options)."""
    return [flag for option in tree.options for flag in option.flags if flag not in {"-h", "--help", "-V", "--version"}]


# --------------------------------------------------------------------------- desktop / metainfo


def render_desktop() -> str:
    """The system menu entry: the per-user template rendered for ``fork-linux`` on PATH."""
    _import_package()
    from fork_linux import desktop_integration

    return desktop_integration._render_menu(list(SYSTEM_COMMAND))


def render_fm_action(kind: str) -> str:
    """A system-wide file-manager action from the per-user templates."""
    if kind not in FM_KINDS:
        raise SystemExit(f"gen-data.py: unknown file-manager action {kind!r} (choose from {', '.join(FM_KINDS)})")
    _import_package()
    from fork_linux import desktop_integration

    content, _mode = desktop_integration._render_kind(kind, list(SYSTEM_COMMAND))
    if GENERATED_NOTE not in content:
        raise SystemExit(f"gen-data.py: the {kind} template lost its GENERATED note")
    return content.replace(GENERATED_NOTE, SYSTEM_NOTE)


def _markup_urls(text: str) -> str:
    """XML-escape a paragraph; URLs lose their scheme (AppStream warns about plain-text URLs).

    ``https://git-fork.com/buy`` becomes ``<code>git-fork.com/buy</code>``: still the buy link,
    readable in every software center. The full URLs are the component's ``<url>`` entries.
    """
    parts = re.split(r"https?://(\S*[^\s.,;:])", text)
    return "".join(
        f"<code>{xml_escape(part)}</code>" if index % 2 else xml_escape(part) for index, part in enumerate(parts)
    )


def render_metainfo(template: str) -> str:
    """The AppStream metainfo from its template and ``credits``."""
    _import_package()
    from fork_linux import APP_ID, APP_NAME, credits

    paragraphs = "\n".join(f"    <p>{_markup_urls(text)}</p>" for text in credits.render_metainfo_paragraphs())
    mapping = {
        "@APP_ID@": APP_ID,
        "@APP_NAME@": xml_escape(APP_NAME),
        "@DESCRIPTION@": paragraphs.strip(),
    }
    text = template
    for key, value in mapping.items():
        if key not in text:
            raise SystemExit(f"gen-data.py: the metainfo template has no {key}")
        text = text.replace(key, value)
    leftover = sorted(set(re.findall(r"@[A-Z_]+@", text)))
    if leftover:
        raise SystemExit(f"gen-data.py: unknown placeholder(s) in the metainfo template: {', '.join(leftover)}")
    return text


# --------------------------------------------------------------------------- completions


def _sh_words(words: list[str]) -> str:
    return " ".join(words)


def _value_flags(tree: Node) -> list[tuple[str, Option, str]]:
    """Every ``(command words, option, flag)`` whose option takes a value, in tree order."""
    return [
        (key, option, flag)
        for key, node in keyed_nodes(tree)
        for option in node.options
        if option.takes_value
        for flag in option.flags
    ]


def _bash_value_body(option: Option) -> str:
    """The bash statements completing ``option``'s value."""
    if option.choices:
        extra = "\n\t\t\t_fork_linux_files" if option.value_kind == "file" else ""
        return f"\t\t\t_fork_linux_words '{_sh_words(option.choices)}'{extra}\n"
    calls = {"dir": "_fork_linux_dirs", "file": "_fork_linux_files"}
    call = calls.get(option.value_kind)
    return f"\t\t\t{call}\n" if call else ""


def _bash_value_cases(tree: Node) -> list[str]:
    return [
        f'\t\t"{key}|{flag}")\n{_bash_value_body(option)}\t\t\t;;'
        for key, option, flag in _value_flags(tree)
    ]


def render_bash(tree: Node) -> str:
    """bash completion for ``fork-linux`` and ``fork``."""
    node_cases: list[str] = []
    for key, node in keyed_nodes(tree):
        opts, vopts, subs, pos, pos_choices = _node_words(node)
        node_cases.append(
            f'\t\t"{key}")\n'
            f"\t\t\t_fl_opts='{opts}'\n"
            f"\t\t\t_fl_vopts='{vopts}'\n"
            f"\t\t\t_fl_subs='{subs}'\n"
            f"\t\t\t_fl_pos={pos}\n"
            f"\t\t\t_fl_pos_words='{pos_choices}'\n"
            "\t\t\t;;"
        )
    fork_opts = _sh_words(["-h", "--help", "-V", "--version", *[f for f in global_flags(tree) if f != "--json"]])
    body = "\n".join(node_cases)
    values = "\n".join(_bash_value_cases(tree))
    return f"""# bash completion for fork-linux and fork -*- shell-script -*-
# {HEADER}

_fork_linux_words() {{
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -W "$1" -- "$cur")
}}

_fork_linux_files() {{
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -f -- "$cur")
}}

_fork_linux_dirs() {{
	local word
	while IFS= read -r word; do
		COMPREPLY+=("$word")
	done < <(compgen -d -- "$cur")
}}

# _fork_linux_node KEY: the options, value options, subcommands and positionals of a command.
_fork_linux_node() {{
	case "$1" in
{body}
		*)
			_fl_opts=''
			_fl_vopts=''
			_fl_subs=''
			_fl_pos=1
			_fl_pos_words=''
			;;
	esac
}}

# _fork_linux_value KEY OPTION: complete the value of OPTION.
_fork_linux_value() {{
	case "$1|$2" in
{values}
		*)
			_fork_linux_files
			;;
	esac
}}

_fork_linux_takes_value() {{
	local option
	for option in $_fl_vopts; do
		[[ "$option" == "$1" ]] && return 0
	done
	return 1
}}

_fork_linux() {{
	local cur prev key="" word i skip=0 _fl_opts _fl_vopts _fl_subs _fl_pos _fl_pos_words
	COMPREPLY=()
	cur="${{COMP_WORDS[COMP_CWORD]}}"
	prev=""
	if ((COMP_CWORD > 0)); then
		prev="${{COMP_WORDS[COMP_CWORD - 1]}}"
	fi
	_fork_linux_node ""
	for ((i = 1; i < COMP_CWORD; i++)); do
		word="${{COMP_WORDS[i]}}"
		if ((skip)); then
			skip=0
			continue
		fi
		case "$word" in
			--)
				_fork_linux_files
				return 0
				;;
			-*)
				if [[ "$word" != *=* ]] && _fork_linux_takes_value "$word"; then
					skip=1
				fi
				continue
				;;
		esac
		if [[ -n "$_fl_subs" ]]; then
			key="${{key:+$key }}$word"
			_fork_linux_node "$key"
		fi
	done
	if ((skip)); then
		_fork_linux_value "$key" "$prev"
		return 0
	fi
	if [[ "$cur" == -* ]]; then
		_fork_linux_words "$_fl_opts"
	elif [[ -n "$_fl_subs" ]]; then
		_fork_linux_words "$_fl_subs"
	elif [[ -n "$_fl_pos_words" ]]; then
		_fork_linux_words "$_fl_pos_words"
	elif ((_fl_pos)); then
		_fork_linux_files
	fi
	return 0
}}

_fork_linux_fork() {{
	local cur prev
	COMPREPLY=()
	cur="${{COMP_WORDS[COMP_CWORD]}}"
	prev=""
	if ((COMP_CWORD > 0)); then
		prev="${{COMP_WORDS[COMP_CWORD - 1]}}"
	fi
	if [[ "$prev" == "--prefix" ]]; then
		_fork_linux_dirs
	elif [[ "$cur" == -* ]]; then
		_fork_linux_words '{fork_opts}'
	else
		if ((COMP_CWORD == 1)); then
			_fork_linux_words 'open'
		fi
		_fork_linux_files
	fi
	return 0
}}

complete -o filenames -F _fork_linux fork-linux
complete -o filenames -F _fork_linux_fork fork
"""


def _zsh_quote(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


def _node_words(node: Node) -> tuple[str, str, str, str, str]:
    """``(options, value options, subcommands, positional flag, positional choices)`` of a node."""
    opts = _sh_words([flag for option in node.options for flag in option.flags])
    vopts = _sh_words([flag for option in node.options if option.takes_value for flag in option.flags])
    subs = _sh_words([name for name, _help, _child in node.subcommands])
    pos_choices = _sh_words([choice for _m, _h, choices in node.positionals for choice in choices])
    return opts, vopts, subs, "1" if node.positionals else "0", pos_choices


def _zsh_value_body(option: Option) -> str:
    """The zsh statement completing ``option``'s value."""
    if option.choices:
        extra = "; _files" if option.value_kind == "file" else ""
        return f"compadd -- {_sh_words(option.choices)}{extra}"
    return {"dir": "_files -/", "file": "_files"}.get(option.value_kind, "_message 'value'")


def render_zsh(tree: Node) -> str:
    """zsh completion for ``fork-linux`` and ``fork``."""
    node_cases: list[str] = []
    for key, node in keyed_nodes(tree):
        opts, vopts, subs, pos, pos_choices = _node_words(node)
        node_cases.append(
            f"    {_zsh_quote(key)})\n"
            f"      opts=({opts}); vopts=({vopts}); subs=({subs}); pos={pos}; pos_words=({pos_choices}) ;;"
        )
    value_cases = [
        f"    {_zsh_quote(f'{key}|{flag}')}) {_zsh_value_body(option)} ;;"
        for key, option, flag in _value_flags(tree)
    ]
    fork_opts = _sh_words(["-h", "--help", "-V", "--version", *[f for f in global_flags(tree) if f != "--json"]])
    nodes_body = "\n".join(node_cases)
    values_body = "\n".join(value_cases)
    return f"""#compdef fork-linux fork
# zsh completion for fork-linux and fork.
# {HEADER}

_fork_linux_node() {{
  case $1 in
{nodes_body}
    *) opts=(); vopts=(); subs=(); pos=1; pos_words=() ;;
  esac
}}

_fork_linux_value() {{
  case "$1|$2" in
{values_body}
    *) _files ;;
  esac
}}

_fork_linux_main() {{
  local -a opts vopts subs pos_words
  local pos key="" word skip=0 i
  _fork_linux_node ""
  for (( i = 2; i < CURRENT; i++ )); do
    word=${{words[i]}}
    if (( skip )); then
      skip=0
      continue
    fi
    case $word in
      --) _files; return ;;
      -*=*) continue ;;
      -*) (( ${{vopts[(Ie)$word]}} )) && skip=1; continue ;;
    esac
    if (( ${{#subs}} )); then
      key=${{key:+$key }}$word
      _fork_linux_node "$key"
    fi
  done
  if (( skip )); then
    _fork_linux_value "$key" "${{words[CURRENT-1]}}"
  elif [[ ${{words[CURRENT]}} == -* ]]; then
    compadd -- $opts
  elif (( ${{#subs}} )); then
    compadd -- $subs
  elif (( ${{#pos_words}} )); then
    compadd -- $pos_words
  elif (( pos )); then
    _files
  fi
}}

_fork_linux_fork() {{
  if [[ ${{words[CURRENT-1]}} == --prefix ]]; then
    _files -/
  elif [[ ${{words[CURRENT]}} == -* ]]; then
    compadd -- {fork_opts}
  else
    (( CURRENT == 2 )) && compadd -- open
    _files
  fi
}}

case $service in
  fork) _fork_linux_fork ;;
  *) _fork_linux_main ;;
esac
"""


def _fish_escape(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish_option(command: str, condition: str, option: Option) -> str:
    parts = [f"complete -c {command}"]
    if condition:
        parts.append(f"-n {_fish_escape(condition)}")
    for flag in option.flags:
        if flag.startswith("--"):
            parts.append(f"-l {flag[2:]}")
        else:
            parts.append(f"-s {flag[1:]}")
    if option.takes_value:
        parts.append("-r")
        if option.choices:
            parts.append(f"-a {_fish_escape(' '.join(option.choices))}")
        if option.value_kind in {"file", "dir"}:
            parts.append("-F")
    if option.help:
        parts.append(f"-d {_fish_escape(option.help)}")
    return " ".join(parts)


def _fish_own_options(node: Node, condition: str, global_set: set[str]) -> list[str]:
    """``complete`` lines for the options of ``node`` that are not global options."""
    return [
        _fish_option("fork-linux", condition, option)
        for option in node.options
        if not set(option.flags) <= global_set
    ]


def _fish_positionals(node: Node, condition: str) -> list[str]:
    """``complete`` lines for the positional arguments of ``node``."""
    choices = [choice for _m, _h, cs in node.positionals for choice in cs]
    if choices:
        return [f"complete -c fork-linux -n {_fish_escape(condition)} -a {_fish_escape(' '.join(choices))}"]
    if node.positionals:
        return [f"complete -c fork-linux -n {_fish_escape(condition)} -F"]
    return []


def _fish_command(name: str, help_text: str, child: Node, global_set: set[str]) -> list[str]:
    """``complete`` lines for one top-level command, its options and its subcommands."""
    lines = [f"complete -c fork-linux -n '__fish_use_subcommand' -a {name} -d {_fish_escape(help_text)}"]
    seen_cmd = f"__fish_seen_subcommand_from {name}"
    lines.extend(_fish_own_options(child, seen_cmd, global_set))
    sub_names = [sub for sub, _h, _c in child.subcommands]
    if not sub_names:
        return lines + _fish_positionals(child, seen_cmd)
    no_sub = f"{seen_cmd}; and not __fish_seen_subcommand_from {' '.join(sub_names)}"
    for sub, sub_help, grandchild in child.subcommands:
        lines.append(f"complete -c fork-linux -n {_fish_escape(no_sub)} -a {sub} -d {_fish_escape(sub_help)}")
        seen_sub = f"{seen_cmd}; and __fish_seen_subcommand_from {sub}"
        lines.extend(_fish_own_options(grandchild, seen_sub, global_set))
        lines.extend(_fish_positionals(grandchild, seen_sub))
    return lines


def render_fish(tree: Node) -> str:
    """fish completion for ``fork-linux`` and ``fork``."""
    lines = [
        "# fish completion for fork-linux and fork.",
        f"# {HEADER}",
        "",
        "complete -c fork-linux -f",
    ]
    lines.extend(_fish_option("fork-linux", "", option) for option in tree.options)
    global_set = set(global_flags(tree)) | {"-h", "--help"}
    for name, help_text, child in tree.subcommands:
        lines.extend(_fish_command(name, help_text, child, global_set))
    lines.extend(
        [
            "",
            "# fork [OPTIONS] [PATH...] / fork open PATH...: fork-linux's global options, then paths.",
            "complete -c fork -F",
            "complete -c fork -n '__fish_use_subcommand' -a open -d 'open repositories in Fork'",
            "complete -c fork -s h -l help -d 'show help and exit'",
            "complete -c fork -s V -l version -d 'show the version and exit'",
        ]
    )
    lines.extend(
        _fish_option("fork", "", option)
        for option in tree.options
        if not set(option.flags) & {"--json", "-h", "--help", "-V", "--version"}
    )
    return "\n".join(lines) + "\n"


def render_completions(shell: str, tree: Node | None = None) -> str:
    """The completion script for ``shell``."""
    node = load_tree() if tree is None else tree
    renderers = {"bash": render_bash, "zsh": render_zsh, "fish": render_fish}
    if shell not in renderers:
        raise SystemExit(f"gen-data.py: unknown shell {shell!r} (choose from bash, zsh, fish)")
    return renderers[shell](node)


# --------------------------------------------------------------------------- manual pages


def roff(text: str) -> str:
    """Escape plain text for roff (backslashes, hyphens, leading control characters)."""
    out = text.replace("\\", "\\e").replace("-", "\\-")
    lines = []
    for line in out.split("\n"):
        if line.startswith((".", "'")):
            line = "\\&" + line
        lines.append(line)
    return "\n".join(lines)


def _option_label(option: Option) -> str:
    flags = ", ".join(f"\\fB{roff(flag)}\\fR" for flag in option.flags)
    if option.takes_value:
        flags += f" \\fI{roff(option.metavar)}\\fR"
    return flags


def _synopsis(node: Node) -> str:
    parts = [f"\\fBfork\\-linux {roff(node.key)}\\fR", "[\\fIOPTIONS\\fR]"]
    if node.subcommands:
        parts.append("\\fISUBCOMMAND\\fR")
    for metavar, _help, _choices in node.positionals:
        parts.append(f"[\\fI{roff(metavar.upper())}\\fR]")
    return " ".join(parts)


def _man_header(name: str, section_title: str) -> list[str]:
    return [
        f".\\\" {HEADER}",
        f'.TH {name.upper()} 1 "" "Fork for Linux (unofficial)" "{section_title}"',
    ]


def _credits_section() -> list[str]:
    from fork_linux import credits

    return [
        ".SH CREDITS AND DISCLAIMER",
        roff(
            f"Fork is proprietary, paid software made by {credits.developers_text()} "
            f"({credits.LINKS['website']}). Please buy a license at {credits.LINKS['buy']}."
        ),
        ".PP",
        roff(credits.disclaimer()),
        ".PP",
        roff(
            f"Fork for Linux (unofficial) downloads the official installer from {credits.INSTALLER_HOST} "
            "on your machine and never redistributes, patches or decompiles Fork. "
            f"Fork's license (EULA): {credits.LINKS['license']}."
        ),
    ]


def _man_command(node: Node, aliases: list[str], global_set: set[str]) -> list[str]:
    """The ``.SS`` section of one command: synopsis, help, its own options and positionals."""
    title = node.key
    if len(aliases) > 1:
        title += " (alias: " + ", ".join(aliases[1:]) + ")"
    lines = [f".SS {roff(title)}", _synopsis(node), ".PP", roff(node.help or "")]
    for option in node.options:
        if not set(option.flags) <= global_set:
            lines += [".TP", _option_label(option), roff(option.help or "")]
    for metavar, help_text, choices in node.positionals:
        text = help_text
        if choices:
            text = (text + " " if text else "") + "One of: " + ", ".join(choices) + "."
        lines += [".TP", f"\\fI{roff(metavar.upper())}\\fR", roff(text)]
    return lines


def _man_commands(tree: Node) -> list[str]:
    """The COMMANDS section of fork-linux(1)."""
    aliases: dict[int, list[str]] = {}
    for name, _help, child in tree.subcommands:
        aliases.setdefault(id(child), []).append(name)
    global_set = set(global_flags(tree)) | {"-h", "--help"}
    lines = [".SH COMMANDS"]
    for node in walk(tree)[1:]:
        lines += _man_command(node, aliases.get(id(node), []), global_set)
    return lines


def render_man_fork_linux(tree: Node) -> str:
    """``fork-linux(1)``."""
    from fork_linux import credits
    from fork_linux.errors import ExitCode

    lines = _man_header("fork-linux", "User Commands")
    lines += [
        ".SH NAME",
        "fork\\-linux \\- run the official Fork for Windows git client under Wine (unofficial wrapper)",
        ".SH SYNOPSIS",
        "\\fBfork\\-linux\\fR [\\fIGLOBAL OPTIONS\\fR] \\fICOMMAND\\fR [\\fIOPTIONS\\fR] [\\fIARGS\\fR]",
        ".br",
        "\\fBfork\\-linux\\fR \\fB\\-\\-version\\fR | \\fB\\-\\-help\\fR",
        ".SH DESCRIPTION",
    ]
    paragraphs = [roff(paragraph) for paragraph in credits.render_metainfo_paragraphs()]
    lines.append("\n.PP\n".join(paragraphs))
    lines += [
        ".PP",
        roff(
            "The first run sets everything up lazily and resumably: a pinned Wine runtime, "
            "a per-user Wine prefix, Microsoft .NET Framework and the official Fork installer. "
            "Nothing is ever written to ~/.wine."
        ),
        ".SH GLOBAL OPTIONS",
        roff("These options are accepted before or after the command."),
    ]
    for option in tree.options:
        lines += [".TP", _option_label(option), roff(option.help or "")]
    lines += _man_commands(tree)
    lines.append(".SH EXIT STATUS")
    for code in ExitCode:
        lines += [".TP", f"\\fB{int(code)}\\fR", roff(code.name)]
    lines += [
        ".SH FILES",
        ".TP",
        roff("~/.config/fork-linux/config.ini"),
        roff("fork-linux settings."),
        ".TP",
        roff("~/.local/share/fork-linux/prefix/"),
        roff("The Wine prefix fork-linux creates (mode 0700, marker .fork-linux/created-by)."),
        ".TP",
        roff("~/.local/share/fork-linux/runtimes/, ~/.local/share/fork-linux/snapshots/"),
        roff("Managed Wine runtimes and snapshots of Fork's install."),
        ".TP",
        roff("~/.cache/fork-linux/"),
        roff("Downloads and the update feed cache."),
        ".TP",
        roff("~/.local/state/fork-linux/logs/"),
        roff("Logs (fork-linux logs --bundle collects them)."),
        ".SH ENVIRONMENT",
        ".TP",
        "\\fBFORK_LINUX_ALLOW_ROOT\\fR",
        roff("Set to 1 to allow running as root (containers and CI only)."),
        ".TP",
        "\\fBFORK_LINUX_LIBDIR\\fR",
        roff("Directory holding the fork_linux package (overrides the installed one)."),
    ]
    lines += _credits_section()
    lines += [
        ".SH BUGS",
        roff(f"Report wrapper, Wine and Linux problems at {credits.LINKS['project_issues']}, not to Fork support."),
        ".SH SEE ALSO",
        "\\fBfork\\fR(1), \\fBwine\\fR(1), \\fBgit\\fR(1)",
    ]
    return "\n".join(lines) + "\n"


def render_man_fork(tree: Node) -> str:
    """``fork(1)``."""
    lines = _man_header("fork", "User Commands")
    lines += [
        ".SH NAME",
        "fork \\- open repositories in Fork for Linux (unofficial)",
        ".SH SYNOPSIS",
        "\\fBfork\\fR [\\fIOPTIONS\\fR] [\\fIPATH\\fR...]",
        ".br",
        "\\fBfork open\\fR [\\fIOPTIONS\\fR] \\fIPATH\\fR...",
        ".br",
        "\\fBfork\\fR \\fB\\-\\-help\\fR | \\fB\\-\\-version\\fR",
        ".SH DESCRIPTION",
        roff(
            "Open each PATH (a repository, or a file or folder inside one) in Fork. With no PATH, "
            "start Fork. This is a shortcut for 'fork-linux run'; the first run sets everything up. "
            "Use -- before paths that start with '-'."
        ),
        ".SH OPTIONS",
        ".TP",
        "\\fB\\-h\\fR, \\fB\\-\\-help\\fR",
        roff("Show the usage and exit."),
        ".TP",
        "\\fB\\-V\\fR, \\fB\\-\\-version\\fR",
        roff("Show the version and exit."),
    ]
    for option in tree.options:
        if set(option.flags) & {"--json", "-h", "--help", "-V", "--version"}:
            continue
        lines += [".TP", _option_label(option), roff(option.help or "")]
    lines += [
        ".SH EXIT STATUS",
        roff("The exit status of fork-linux run; see fork-linux(1)."),
    ]
    lines += _credits_section()
    lines += [".SH SEE ALSO", "\\fBfork\\-linux\\fR(1)"]
    return "\n".join(lines) + "\n"


def render_man(page: str, tree: Node | None = None) -> str:
    """The manual page ``page`` (``fork-linux`` or ``fork``)."""
    node = load_tree() if tree is None else tree
    if page == "fork-linux":
        return render_man_fork_linux(node)
    if page == "fork":
        return render_man_fork(node)
    raise SystemExit(f"gen-data.py: unknown manual page {page!r} (choose from fork-linux, fork)")


def render_build_info(version: str, flavor: str) -> str:
    """``fork_linux/_build.py``: the version and packaging flavour baked in at build time."""
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit(f"gen-data.py: invalid version {version!r}")
    if not re.fullmatch(r"[a-z0-9][a-z0-9.-]*", flavor):
        raise SystemExit(f"gen-data.py: invalid flavor {flavor!r}")
    return (
        '"""Build information generated by meson (scripts/gen-data.py build-info); do not edit."""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        f'VERSION = "{version}"\n'
        f'FLAVOR = "{flavor}"\n'
    )


# --------------------------------------------------------------------------- committed files


def committed_outputs() -> dict[Path, str]:
    """Every committed generated file and its expected content."""
    tree = load_tree()
    out: dict[Path, str] = {}
    for (kind, name), rel in COMMITTED.items():
        out[rel] = render_completions(name, tree) if kind == "completions" else render_man(name, tree)
    return out


def safe_path(raw: str | Path) -> Path:
    """``raw`` resolved, refused unless it lies in the repository or the working directory.

    Meson runs this script from its build directory and passes paths inside it; ``write`` /
    ``check`` use repository paths. Anything else (``..`` escapes, absolute paths elsewhere,
    symlinks pointing out) is a usage error.
    """
    resolved = Path(os.path.realpath(raw))
    bases = (Path(os.path.realpath(ROOT)), Path(os.path.realpath(os.getcwd())))
    if not any(resolved == base or resolved.is_relative_to(base) for base in bases):
        raise SystemExit(f"gen-data.py: refusing {raw}: outside the repository and the build directory")
    return resolved


def _write(path: str | Path, text: str) -> None:
    target = safe_path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")


def _read(path: str | Path) -> str:
    return safe_path(path).read_text(encoding="utf-8")


def _emit(text: str, out: str | None) -> None:
    if out is None:
        sys.stdout.write(text)
    else:
        _write(out, text)


def _cmd_name(args: argparse.Namespace) -> int:
    _import_package()
    import fork_linux

    print(getattr(fork_linux, args.key))
    return 0


def _cmd_write(_args: argparse.Namespace) -> int:
    for rel, text in committed_outputs().items():
        _write(ROOT / rel, text)
        print(f"wrote {rel}")
    return 0


def _cmd_check(_args: argparse.Namespace) -> int:
    drift = [
        str(rel)
        for rel, text in committed_outputs().items()
        if not (ROOT / rel).is_file() or _read(ROOT / rel) != text
    ]
    if drift:
        print("gen-data.py: out of date (run scripts/gen-data.py write): " + ", ".join(drift), file=sys.stderr)
        return 1
    print("gen-data.py: completions and manual pages are up to date")
    return 0


def _written(render: Callable[[argparse.Namespace], str]) -> Callable[[argparse.Namespace], int]:
    """A handler that writes ``render(args)`` to ``args.out`` (stdout when there is none)."""

    def handler(args: argparse.Namespace) -> int:
        _emit(render(args), args.out)
        return 0

    return handler


HANDLERS: dict[str, Callable[[argparse.Namespace], int]] = {
    "desktop": _written(lambda _args: render_desktop()),
    "metainfo": _written(lambda args: render_metainfo(_read(args.template))),
    "fm-action": _written(lambda args: render_fm_action(args.kind)),
    "build-info": _written(lambda args: render_build_info(args.version, args.flavor)),
    "completions": _written(lambda args: render_completions(args.shell)),
    "man": _written(lambda args: render_man(args.page)),
    "name": _cmd_name,
    "write": _cmd_write,
    "check": _cmd_check,
}


def build_cli() -> argparse.ArgumentParser:
    """The command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("desktop").add_argument("out")
    p_meta = sub.add_parser("metainfo")
    p_meta.add_argument("template")
    p_meta.add_argument("out")
    p_fm = sub.add_parser("fm-action")
    p_fm.add_argument("kind", choices=FM_KINDS)
    p_fm.add_argument("out")
    p_comp = sub.add_parser("completions")
    p_comp.add_argument("shell", choices=("bash", "zsh", "fish"))
    p_comp.add_argument("out", nargs="?")
    p_man = sub.add_parser("man")
    p_man.add_argument("page", choices=("fork-linux", "fork"))
    p_man.add_argument("out", nargs="?")
    p_build = sub.add_parser("build-info")
    p_build.add_argument("version")
    p_build.add_argument("flavor")
    p_build.add_argument("out")
    sub.add_parser("name").add_argument("key", choices=("APP_ID", "APP_NAME", "PACKAGE"))
    sub.add_parser("write")
    sub.add_parser("check")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point."""
    args = build_cli().parse_args(argv)
    return HANDLERS[args.cmd](args)


if __name__ == "__main__":
    raise SystemExit(main())
